services:
  db:
    image: postgres:17
    container_name: hapi-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hapi}
      POSTGRES_USER: ${POSTGRES_USER:-hapi}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-hapi}
    ports:
      - "5432:5432"
    volumes:
      - hapi-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-hapi} -d ${POSTGRES_DB:-hapi}"]
      interval: 5s
      timeout: 5s
      retries: 20

  hapi:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    depends_on:
      db:
        condition: service_healthy
    ports: ["8080:8080"]
    environment:
      # FHIR version
      HAPI_FHIR_VERSION: R4

      # Postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hapi
      SPRING_DATASOURCE_USERNAME: hapi
      SPRING_DATASOURCE_PASSWORD: hapi
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect

      # JVM heap
      JAVA_TOOL_OPTIONS: "-Xms3g -Xmx3g -XX:+UseG1GC"


volumes:
  hapi-data:
  # orthanc-data: